### ISSUE TITLE
Type Error

### ISSUE THREAD

**Issue by sandarutharuneth** [oelin/node-replicate#11]
I have a type error on the console after updating the package from 1.1.6 to 2.0.0
```sh
TypeError: replicate.run is not a function
```

can you help me out with this please?
